### ISSUE TITLE
Feature Request: Implement clipboard feature into `show.py`

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#100]
This file has already implemented [copy to clipboard feature](https://github.com/AmateursLeague/sneaky-package/blob/main/package/graph.py), integrate this feature into `models.py`.

**Requirement**:
- Implementation of clipboard feature into, `models.py`.
- Should only copy the contents into system's clipboard when executed with clipboard argument.

**Example**:
```python
from package.show import display
display("file", 1212, 1)
```
Here' the execution of models feature is same, but with extra argument being passed(i,e. `1`)

1. **Display feature**(**_What we already have!_**):
```python
from pacakge.show import display
display("test", 1212)
```
**Output**:
```bash
print("If it's visible, then it's good to go!")
```

2. **Copy to clipboard feature** (_**Required feature to be implemented**_)

```python
from pacakge.show import display
display("test", 1212, 1)
```
Should copy contents into system's clipboard without displaying the output in console.

The above feature explains the requirement of copy to clipboard feature inside `models.py`.

Share your ideas & thoughts on how you are planning to do this to get assigned!

**Comment by this-is-yaash** [comment]
Assignees are instructed to use the development branch to work on this issue, when getting assigned!

Use the following command!
```python
git fetch origin
git checkout 100-feature-request-implement-clipboard-feature-into-modelspy
```

**Comment by yasheela-alla** [comment]
hey @this-is-yaash, I'd love to workon this issue!

here’s my approach ->

we can implement the clipboard feature in `models.py` using the `pyperclip` library. The `display` function wd accept an optional clipboard arg, which will then copy the content to system clipboard instead of printing it to the console

If this approach works, could you please assign the issue to me?

**Comment by this-is-yaash** [comment]
> hey @this-is-yaash, I'd love to workon this issue!
> 
> here’s my approach ->
> 
> we can implement the clipboard feature in `models.py` using the `pyperclip` library. The `display` function wd accept an optional clipboard arg, which will then copy the content to system clipboard instead of printing it to the console
> 
> If this approach works, could you please assign the issue to me?

sry but using external libs are not allowed, in order to maintain lightweight package and to allow faster execution and insallation.

I would say that you don't have to do anything advanced stuffs, 
just see `graph.py` file and integrate them into models. 

But should execute based on the argument!



In simple terms, everything has already been implemented!
Just try to integrate them into the `models.py`, that's it!

I hope you understand, please raise a question if you don't get i!


> The issue will be assigned to those who come up with the valid explanation of what they plan to do to implement the featue!

**Comment by yasheela-alla** [comment]
Ah, okay! 

so I’ll just take the clipboard logic from `graph.py` and add an extra argument in the `display` function in `models.py` to handle it. So if that argument is passed, it copies to the clipboard instead of doing the usual stuff. 

right?

**Comment by this-is-yaash** [comment]
My idea is to execute it that way, 
```python
from pacakge.models import display
display("test", 1212, 1)
```

if have have any other alternative method to implement, please let me know!

**Comment by ShashwatAgrawal20** [comment]
@yasheela-alla 

You're the wizard for this one! Let's make magic happen! 

![assigned](https://github.com/user-attachments/assets/e4d75fba-9a41-44cc-8917-a1f030c77ab0)

**Comment by yasheela-alla** [comment]
Haha Thank you @ShashwatAgrawal20

**Comment by Iammohitraj2** [comment]
I will like to work for this project

**Comment by Wahid7852** [comment]
its already assigned to @yasheela-alla

**Comment by yashksaini-coder** [comment]
can i work on this issue @this-is-yaash

**Comment by this-is-yaash** [comment]
#119 fixes
