### ISSUE TITLE
Add Metrics Table to README

### ISSUE THREAD

**Issue by neeru24** [AmateursLeague/sneaky-package#102]
### Issue: Add Metrics Table to README

It would enhance the README file significantly to include a table displaying key repository metrics such as the number of stars, forks, pull requests, and any other relevant statistics. This addition will make the repository more informative and visually appealing to users.

### Benefits:

- Improves the overall presentation of the README.
- Encourages contributions by showcasing community involvement.

**Comment by ShashwatAgrawal20** [comment]
Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/db01f22d-b42e-4dd0-a1e4-94fa20608ab2)


**CLOSING**
