### ISSUE TITLE
Auto Commenting on New Issue Creation

### ISSUE THREAD

**Issue by sejals23** [AmateursLeague/sneaky-package#105]
It automatically adds comments to the description of a newly created issue, providing helpful information, context, or reminders. This ensures that all issues include essential details or instructions, improving the quality of reports.

It ensures that comments on issues follow a consistent format or structure. This helps teams maintain a standardized approach to handling issues, reducing confusion and misunderstandings.

Saves Time: Users don’t need to manually add repetitive information or instructions. The automatic comment can include standard guidelines, troubleshooting steps, or links to documentation.

**Comment by Wahid7852** [comment]
I saw this in the repo TwinTrim too, are you trying to do this on multiple repositories to farm points?

**Comment by sejals23** [comment]
I have solved other issues as well and I am raising this issue only in the repository which don't have this feature

**Comment by Wahid7852** [comment]
@this-is-yaash what your views on this? do we really need this?

**Comment by this-is-yaash** [comment]
It does not align with our project! I think we can close this?

**Comment by ShashwatAgrawal20** [comment]
Sorry

![dontneedtoaddress](https://github.com/user-attachments/assets/726db9e8-5c5b-418d-a9b3-950026b50f27)


**CLOSING**
