### ISSUE TITLE
Modify `write.py` to retain original file extension when writing output

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#114]
**`write.py`** reads files with any extension but always writes the output in `.py` format. Modify the module to write the file in the same format as the input file's extension."

[**`write.py`**](https://github.com/AmateursLeague/sneaky-package/blob/main/package/write.py) file link.
Take a look at this code, and try to come up with a way to fix this issue!

**Module of the code for reference:**
```python
    try:
        base_dir = os.path.dirname(__file__)
        snippets_dir = os.path.join(base_dir, "stash")
        pattern = os.path.join(snippets_dir, f"{snippet_name}.*")

        matching_files = glob.glob(pattern)
        
        if not matching_files:
            raise FileNotFoundError(f"No file found with the name.")
        elif len(matching_files) > 1:
            raise ValueError("Multiple files found with the given name.")
        
        snippet_path = os.path.join(snippets_dir, matching_files[0])
        output_path = os.path.join(base_dir, f"{snippet_name}.py")

        shutil.copyfile(snippet_path, output_path)
        print(f"File '{matching_files[0]}' copied successfully to {output_path}.")

    except FileNotFoundError:
        print("File is not found")
```
**Write in `.py`**
```python
        output_path = os.path.join(base_dir, f"{snippet_name}.py")

```
This line is hardcoded, modify the module of the code to write the file in the same format as the input file's extension.

**Comment by Harshvardhan5703** [comment]
I want to resolve this issue.
Have already contacted you through email.

**Comment by this-is-yaash** [comment]
@Harshvardhan5703 I see that you already raised the PR for this!
Let me reviwe that and I'll let you know!

**Comment by Harshvardhan5703** [comment]
Yes sir, do tell me if I have to include something else too.

**Comment by this-is-yaash** [comment]
LGTM!
I'm merging it right away!
