### ISSUE TITLE
Adding Icon on the heading of Sneaky package!!

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [AmateursLeague/sneaky-package#117]
i would like to add a icon in the heading sneaky package in its desciption!!
please assign me with the required labels as per gssoc'24 extended program

**Comment by ShashwatAgrawal20** [comment]
Sorry, I don't see a need to add that, the current README is already pretty good. 

![dontneedtoaddress](https://github.com/user-attachments/assets/860897b1-59ec-4642-8437-7911858745e6)


**CLOSING**
