### ISSUE TITLE
Updating Static Site: GitHub Page

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#121]
### Discussed in https://github.com/AmateursLeague/sneaky-package/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **this-is-yaash** October 16, 2024</sup>
Share your ideas and thoughts here!</div>

Currently, the GitHub page uses the `README.md` file from this repository to display its content. However, I would like to create separate documentation specifically for the GitHub page.

Please share your ideas in the discussion section mentioned above. Once you receive approval there, feel free to leave a comment here.

**Comment by yashksaini-coder** [comment]
Can i work on it @this-is-yaash @ShashwatAgrawal20

**Comment by yashksaini-coder** [comment]
@jindalpriyanshu101

**Comment by this-is-yaash** [comment]
@yashksaini-coder share your ideas and thoughts, on how you are planning craft a documentation for github page

in this #120 discussion section!

**Comment by this-is-yaash** [comment]
https://github.com/AmateursLeague/sneaky-package/discussions/120#discussioncomment-10971122"
Approved!

assigning this issue to you! @yashksaini-coder

**Comment by this-is-yaash** [comment]
make sure to update repo
create new branch on top of `main`
then start working on the issue! 
@yashksaini-coder

**Comment by yashksaini-coder** [comment]
> make sure to update repo create new branch on top of `main` then start working on the issue! @yashksaini-coder

okh understood

**Comment by this-is-yaash** [comment]
@yashksaini-coder any updates on this issue?

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder any updates on this issue?

yep I have successfully blown the docs on my end, Have to re-install desktop

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder any updates on this issue?

yeah I am trying the MKdocs

**Comment by this-is-yaash** [comment]
@yashksaini-coder, I don't think this falls under documentation, it's more related to the static site category. So, I'm raising the issue to **`level3`**.
