### ISSUE TITLE
Add Metrics Table to README

### ISSUE THREAD

**Issue by neeru24** [AmateursLeague/sneaky-package#122]
To provide a quick overview of the project’s popularity and community engagement, we should add a metrics table to the README file. This table will display key statistics, including the number of pull requests, stars, and forks, helping new users and contributors understand the project’s activity level.

Action Items:

- Gather current metrics from GitHub.
- Implement the metrics table in the README file.
- Automatically update the table to reflect accurate counts.

Kindly assign me this

**Comment by ShashwatAgrawal20** [comment]
**HEY @neeru24  YOU HAVE TO STOP SPAMMING THIS ISSUE.**

duplicate #102 

![stop-spamming](https://github.com/user-attachments/assets/44f0f84c-d36e-476d-9776-7e31bb9833ad)

**CLOSING**
