### ISSUE TITLE
GitHub Workflow: Enforce using `Black` as code formatter

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#123]
I want to enforce using **`Black`** as the default code formatter in this repository. Regardless of whether the PR is formatted with **`Black`**, the GitHub workflow should automatically apply the linter to the `package/` directory.

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me? @this-is-yaash

**Comment by Wahid7852** [comment]
How will you tackle this?

**Comment by prisha-sh** [comment]
hey @this-is-yaash kindly assign it to me !! I would configure a GitHub Action to automatically run and apply Black to the `package/` directory on every push or pull request.

**Comment by Wahid7852** [comment]
> hey @this-is-yaash kindly assign it to me !! I would configure a GitHub Action to automatically run and apply Black to the `package/` directory on every push or pull request.

Show me an example of how it will be working and I will assign you.

**Comment by this-is-yaash** [comment]
@prisha-sh any updates?

**Comment by yashksaini-coder** [comment]
can I give a try on this issue later ? @this-is-yaash

**Comment by Wahid7852** [comment]
one at a time yash

**Comment by tannuiscoding** [comment]
Hey, I'd like to work on this issue.

**Comment by yashksaini-coder** [comment]
> Hey, I'd like to work on this issue.

Assign her @tannuiscoding

**Comment by Kaos599** [comment]
hey can i work on this @this-is-yaash @Wahid7852 ? i will implement it like this [https://github.com/Kaos599/100DaysOfCode/blob/main/.github/workflows/black.yml](black.yml)

**Comment by Kaos599** [comment]
@this-is-yaash i have already tried to complete this. In this [Example](https://github.com/Kaos599/100DaysOfCode/blob/main/.github/workflows/black.yml).

if possible can you assign this to me?

**Comment by techy4shri** [comment]
@Kaos599 as you can see that this is an already assigned issue with an open PR, this cannot be assigned to you. Unless the PR is not merged or any other situation, you will have to look for other open issues which have the up-for-grab tag or riase your own.

**Comment by Kaos599** [comment]
> @Kaos599 as you can see that this is an already assigned issue with an open PR, this cannot be assigned to you. Unless the PR is not merged or any other situation, you will have to look for other open issues which have the up-for-grab tag or riase your own.

okay sure
