### ISSUE TITLE
ADD GSSOC AND HACKTOBERFEST BANNER ON THE README

### ISSUE THREAD

**Issue by alo7lika** [AmateursLeague/sneaky-package#124]
### Title of the Issue (ADD GSSOC AND HACKTOBERFEST BANNER ON THE README)
- [x] **Have you named the issue title clearly and descriptively?**  
- [x] **Have you searched for existing issues in the project to avoid duplicates?**  

### Description
The README file currently lacks banners for GSSOC (GirlScript Summer of Code) and Hacktoberfest. Adding these banners would increase visibility and participation from open-source contributors. The banners will also highlight that the project is a part of these events.

### Steps to Reproduce
1. Open the project repository.
2. Navigate to the README file.
3. Observe that there are no banners for GSSOC and Hacktoberfest.

### Changes Expected
I intend to add official GSSOC and Hacktoberfest banners at the top of the README file. This will include updating the markdown with image links and ensuring they are appropriately positioned for visibility.

### Screenshots / Logs
N/A 

### Related Issues or Pull Requests
None at the moment.

### Environment
- Operating System: Windows 11
- Browser: Chrome Version 117.0.5938.88
- Framework/Platform: GitHub

### Checklist
- [x] I have followed the issue title guidelines.
- [x] I have included a clear and detailed description.
- [x] I have provided necessary logs, screenshots, or other files (if applicable).
- [x] I am a GSSOC contributor.
- [x] I have mentioned related issues or pull requests if any.
- [x] I have provided details about the environment where the issue was observed.

**Comment by alo7lika** [comment]
@AmateursLeague ASSIGN ME THIS TASK. ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST. 
THANK YOU!

**Comment by NishantHegde2305** [comment]
Assign me this work

**Comment by ShashwatAgrawal20** [comment]
This contribution won't add any value to the project.

Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/c922570a-4f25-4e2b-8a04-8fc703ff1c7c)


**CLOSING**
