### ISSUE TITLE
Test Case: Write test cases for `scrap.py` & `display.py`

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#125]
### Features and Their Test Cases
| Feature        | Test Case |
| -------------- | --------- |
| `clip.py`      | ✅        |
| **`display.py`** | ❌      |
| **`scrap.py`**   | ❌      |
| `show.py`      | ✅        |
| `write.py`     | ✅        |

- [Directory of Features](https://github.com/AmateursLeague/sneaky-package/tree/main/package)
- [Directory of Test Cases](https://github.com/AmateursLeague/sneaky-package/tree/main/tests)

Please explore the `package/` directory to understand what `display.py` and `scrap.py` do, and write test cases for them!

**Note:**  
- `scrap.py` is a bit tricky, so feel free to reach out to mentors and project admins (PAs) for assistance.  
- Make sure to add your test cases under the `tests/` directory.

**Comment by Ki1er** [comment]
workin on this

**Comment by tannuiscoding** [comment]
I'd like to write the test cases for these files. Assign me the issue under gssocext label.

**Comment by yashksaini-coder** [comment]
> I'd like to write the test cases for these files. Assign me the issue under gssocext label.

she got really good exp in writing test cases I vote to give this issue to @this-is-yaash

**Comment by this-is-yaash** [comment]
@tannuiscoding would you like to work on this issue?

**Comment by tannuiscoding** [comment]
@this-is-yaash I'd love to work on this. 🤩

**Comment by this-is-yaash** [comment]
@tannuiscoding you are assigned!
