### ISSUE TITLE
Bug [Component] Web scrape  

### ISSUE THREAD

**Issue by yashksaini-coder** [AmateursLeague/sneaky-package#128]
### Title of the Issue
- [X] **Have you named the issue title clearly and descriptively?**
- [X] **Have you searched for existing issues in the project to avoid duplicates?**  

### Description
The `grab` function of the scrap.py is not working properly as it intends to do so.

### Steps to Reproduce

1. Reinstalling the correct python packages
2. writing the scrape logic with exception handling
3. Writing test cases for each method

### Changes Expected
The code should extract the text an copy it to clipboard

### Checklist
- [X] I have followed the issue title guidelines.
- [X] I have included a clear and detailed description.
- [X] I have provided necessary logs, screenshots, or other files.
- [X] I am a GSSOC contributor.
- [X] I have mentioned related issues or pull requests if any.
- [X] I have provided details about the environment where the issue was observed.

**Comment by yashksaini-coder** [comment]
@this-is-yaash can you review this issue & assign it to me

**Comment by ShashwatAgrawal20** [comment]
hey @yashksaini-coder, what's wrong with the `grab` function in the `scrap.py`? 

It's working for me tho!

**Comment by yashksaini-coder** [comment]
the scrape functionality is not working

**Comment by Wahid7852** [comment]
show us what the intended functionality of scrape is and how is it not working please

**Comment by yashksaini-coder** [comment]
![image](https://github.com/user-attachments/assets/aee4436f-d075-416a-8f89-7025e01cf657)

Few errors I discovered are:- 

wrong error handling
not properly returning html_content 
unclear return type

@ShashwatAgrawal20 @Wahid7852

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder hey, that scrap feature is specific to the web-app. It primarily uses https://cl1p.net, to perform scraping operations!
> 
> In simple terms, we can use the feature only when we have data avail on the site!

so still it lacks few methods

**Comment by this-is-yaash** [comment]
@yashksaini-coder could you please briefly explain what's lacking in the feature and how you plan to improve it?
