### ISSUE TITLE
Exception Handling in python files

### ISSUE THREAD

**Issue by Sai-ganesh-0004** [AmateursLeague/sneaky-package#134]
### Exception Handling in python files
- [x] **Have you named the issue title clearly and descriptively?**  
- [x] **Have you searched for existing issues in the project to avoid duplicates?**  
  

### Description

Implement structured exception handling across all Python files in the project to improve error management, logging, and user experience.

### Affected Sections (Code or Documentation)

- [x] Code

### Impact Analysis

This change will enhance the robustness of the codebase by ensuring that errors are logged appropriately, user-friendly messages are displayed, and unhandled exceptions are managed through a global error handler. It may require modifications to existing functions and API interactions.

### Steps to Reproduce (if applicable)

1. Introduce deliberate errors in various Python files (e.g., API calls, file operations).
2. Run the application and observe the error handling behavior.
3. Verify that the logging and user messages are clear and informative.

### Additional Context

This initiative aims to follow best practices in error handling, which is crucial for maintaining application stability.

### Checklist
- [x] I have followed the issue title guidelines.
- [x] I have categorized the change as code or documentation.
- [x] I have included a clear and detailed description of the change.
- [x] I have specified the affected sections.
- [x] I have provided an impact analysis.
- [x] I have included steps to reproduce (if applicable).
- [x] I have added any additional context or screenshots (if applicable).
- [x] I am a GSSOC contributor.
- [x] I have read and understood the GSSOC guidelines.
- [x] I have adhered to the code of conduct.

**Comment by BharadwajShivanya** [comment]
I want to contribute

**Comment by Wahid7852** [comment]
@Sai-ganesh-0004 are you sure that the current program does not have exception handling in it?
