### ISSUE TITLE
Bug: create & automate Clip function for making clips

### ISSUE THREAD

**Issue by yashksaini-coder** [AmateursLeague/sneaky-package#135]
### Title of the Issue
- [X] **Have you named the issue title clearly and descriptively?**
- [X] **Have you searched for existing issues in the project to avoid duplicates?**  

### Steps to Reproduce

- Add create_clip function to generate clips

### Changes Expected
It will create clips that can be created & then retrieved from upload & scrap.

### Checklist
- [X] I have followed the issue title guidelines.
- [X] I have included a clear and detailed description.
- [X] I have provided necessary logs, screenshots, or other files.
- [X] I am a GSSOC contributor.
- [X] I have mentioned related issues or pull requests if any.
- [X] I have provided details about the environment where the issue was observed.

**Comment by yashksaini-coder** [comment]
@this-is-yaash can you assign me this issue, with proper labels. 

The main problem is that the upload function is not complete it sends the url_name & text, but the clip is not created as it needs user response, so I will add code-snippet that can create clip and then fetch the contents of the clip.net

**Comment by yashksaini-coder** [comment]
Also to automate the clip create functionality using the `https://cl1p.net/` with the time limit for how   long will it be available for ?

**Comment by yashksaini-coder** [comment]
@this-is-yaash assign this issue

**Comment by this-is-yaash** [comment]
#128 should I close this issue? 
@yashksaini-coder

**Comment by yashksaini-coder** [comment]
> #128 should I close this issue? @yashksaini-coder

yeah that's once crude
