### ISSUE TITLE
[Test Suite] Optimize test structure for readability and efficiency

### ISSUE THREAD

**Issue by RanitDERIA** [AmateursLeague/sneaky-package#138]
## Improve Test Structure by Using Fixtures and Consolidating Monkeypatch Setup
- [x] **Have you named the issue title clearly and descriptively?**  
- [x] **Have you searched for existing issues in the project to avoid duplicates?**

### Description
The current test code structure can be improved for better readability, maintainability, and performance. Specifically:

- Mock functions are defined globally, making it difficult to reuse or modify them for different tests.
- Repetitive `monkeypatch` setup across multiple tests introduces redundancy.
- Test function names could be made more descriptive to clarify the scenarios being tested.
- Using a context manager for `monkeypatch` can help ensure patches are applied within a specific scope, improving readability and safety.

### Refactoring suggestions:

- Convert mock functions into pytest fixtures for better reusability.
- Consolidate repetitive `monkeypatch` code into a helper fixture.
- Rename test functions for more descriptive naming.
- Use lambda expressions for `glob` mocks to simplify patching in tests.

### Affected Sections (Code or Documentation)

- [x] Code
- [ ] Documentation

### Impact Analysis
This refactoring will enhance the readability and maintainability of the test code. It will reduce redundancy, making future updates easier and more straightforward. By adopting a more modular and fixture-based approach, it will also improve code clarity and organization, minimizing the risk of unintended behavior due to scattered patches.

### Steps to Reproduce (if applicable)
N/A - This is a refactor issue for improving code quality, not a bug fix.

### Additional Context
The proposed improvements include:

1. Converting global mock functions to fixtures to clean up the test code.
2. Creating a helper fixture for repetitive `monkeypatch` setup.
3. Simplifying `glob` mocks using lambdas and naming tests more descriptively.
4. Using constants for sensitive values, making them easy to update.

### Checklist
- [x] I have followed the issue title guidelines.
- [x] I have categorized the change as code or documentation.
- [x] I have included a clear and detailed description of the change.
- [x] I have specified the affected sections.
- [x] I have provided an impact analysis.
- [ ] I have included steps to reproduce (if applicable).
- [x] I have added any additional context or screenshots (if applicable).
- [x] I am a GSSOC contributor.
- [x] I have read and understood the GSSOC guidelines.
- [x] I have adhered to the code of conduct.

**Comment by ShashwatAgrawal20** [comment]
hey @RanitDERIA we're fine with the current implementation of the test cases as of now. 

Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/14b2059c-9db8-444b-84ff-23069964c432)


**CLOSING**
