### ISSUE TITLE
Enhancements: Improving the sneaky-package

### ISSUE THREAD

**Issue by shubhagarwal1** [AmateursLeague/sneaky-package#140]
I propose to add detailed features, and i request PA to allow me to complete these in 2 PRS

 **Improved Documentation**
- Add a FAQ Section: Compile common questions and answers to help users understand the package better.
- Provide More Examples: Add more usage examples in the documentation to illustrate different functionalities.

**Command-Line Arguments**
- Enhance CLI Options: Add command-line arguments for commonly used features, making it easier for users to invoke them without needing to modify code.

**Comment by ShashwatAgrawal20** [comment]
hey @shubhagarwal1, this doesn't add any value to the project. 

Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/68159971-c203-44bf-a1b3-35eb2c5250e6)


**CLOSING**
