### ISSUE TITLE
Toggle Button for light and Dark switching theme

### ISSUE THREAD

**Issue by siri-chandana-macha** [AmateursLeague/sneaky-package#146]
I want to add  the toggle button can enhance its intuitiveness for users. This change will lead to easier navigation and greater satisfaction with the interface.

@AmateursLeague
 please kindly assign this issue under gsoc-extd , hacktoberfest , hacktoberfest-accepted and level2

**Comment by this-is-yaash** [comment]
This is an invalid issue and it's not relevant to the project.

Please conduct proper research and raise the issues, thank you!
