### ISSUE TITLE
fix: 'Edit on' Link Leads to File Not Found on Deployed Website

### ISSUE THREAD

**Issue by PalankiMeghana** [AmateursLeague/sneaky-package#150]
### Description
The "Edit on" hyperlink on the deployed website leads to a "File Not Found" page. After clicking the "Go to default branch" button, users are redirected to the correct page. This can cause confusion, and the issue should be addressed by updating the hyperlink to directly point to the correct file.

### Affected Sections (Code or Documentation)
- Code

### Impact Analysis
This change will improve user experience by removing the extra step of clicking the "Go to default branch" button. The change is expected to be low-risk, but it’s essential to verify that the correct branch is always linked.

### Steps to Reproduce (if applicable)

1. Visit the deployed website.
2. Click the "Edit on" hyperlink.
3. Observe the "File Not Found" error.
4. Click the "Go to default branch" button to reach the correct file.

 ### Additional Context

The issue likely arises from the hyperlink pointing to an unavailable branch or file. Fixing the routing should resolve the 

###Screenshots

on clicking this 
![image](https://github.com/user-attachments/assets/f6bfe757-5ff9-4832-901a-811cecc80749)
it is showing this  
![image](https://github.com/user-attachments/assets/bee6f60a-adaf-4e0c-a39c-46dfb363c713)
but it is expected to show this 
![image](https://github.com/user-attachments/assets/4891e2bd-2720-4386-a429-53efc88d96a5)
 
@this-is-yaash I would like to make these changes please assign me

**Comment by techy4shri** [comment]
@Wahid7852 @jindalpriyanshu101 @this-is-yaash this is a minor issue.

**Comment by this-is-yaash** [comment]
@PalankiMeghana thanks for pointing out!
However, we don't need to address that issue right now.
That component needs to be removed from the page sooner, but I've kept that on hold.

Thanks for showing interest in our project. Please check out the other issues and leave a comment with your proposal if you want to work on that, we'll get you assigned!
