### ISSUE TITLE
Build Script: Write a script to install the required dependencies.

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#157]
### Steps to Complete Before Writing the Script:
1. [Review the prerequisites & Installation Section](https://github.com/AmateursLeague/sneaky-package/blob/main/docs/PyPi_Setup.md#2-pre-requisites).
2. Create an `install.sh` file in the project's root directory.

### Task:
Write the script(`install.sh`) to install the prerequisites mentioned in the "[Review the prerequisites & Installation Section](https://github.com/AmateursLeague/sneaky-package/blob/main/docs/PyPi_Setup.md#2-pre-requisites)" section. 

The script should execute the installation process and handle any errors smoothly.

> The script's level will be upgraded from **`lvl1`** to **`lvl2`** based on its quality, including readability and error handling.

**Comment by Aum8** [comment]
Hi! I am GSSOC contributor. Can you assign me this issue?
I am going to write a script to install the mentioned prequisites in the PyPi_setup.md file.

**Comment by this-is-yaash** [comment]
@Aum8 assigned to you!

**Comment by this-is-yaash** [comment]
fixes #166
