### ISSUE TITLE
Theme Change Button

### ISSUE THREAD

**Issue by JagritiChopra** [AmateursLeague/sneaky-package#158]
### Title of the Issue Theme Change Option
- [X ] **Have you named the issue title clearly and descriptively?**
- [X ] **Have you searched for existing issues in the project to avoid duplicates?**

### Description

I hsve noticed there is no option for theme change like switching from dark to light or system's theme

### Approach to Creating This Feature

Create a Function to Change Themes: Write a function that updates the style variables based on the selected theme and applies them to all GUI elements.

### Benefits

Makes it more user friendly

### Additional Context

Pls assign this to me under gssoc tag

### Checklist
- [X ] I have followed the issue title guidelines.
- [ X] I have clearly described the feature and its approach.
- [X ] I have explained the benefits of this feature.
- [ ] I have added references or social links, where applicable.
- [ ] I have provided additional context, if necessary.
- [X ] I have read the GSSOC guidelines and understand the contribution process.
- [X ] I have checked for existing issues and pull requests to avoid duplicates.

**Comment by this-is-yaash** [comment]
@JagritiChopra sorry, we're using static site and we don't need to change the theme (for now).
I'll be closing this issue.
