### ISSUE TITLE
add gssoc fest logo GitHub repo stats in the readme Complete this process in GitHub using markdown !!

### ISSUE THREAD

**Issue by REHAN-18** [AmateursLeague/sneaky-package#163]
### Title of the Issue
- [X] **Have you named the issue title clearly and descriptively?**
- [X] **Have you searched for existing issues in the project to avoid duplicates?**

I Want to add gssoc fest logo & githuib repo stats , Complete this process in GitHub
### Approach to Creating This Feature

it will enhance the repo help the contributor 
<img width="809" alt="Screenshot 2024-10-26 at 11 50 42 PM" src="https://github.com/user-attachments/assets/3578918c-8ef9-4ce8-99d7-f1bef1e1b749">

### Benefits

repo will be enhances help the contribitor how to contribute by the Complete this process in GitHub
like this 
<img width="834" alt="Screenshot 2024-10-26 at 11 48 23 PM" src="https://github.com/user-attachments/assets/4a1c5282-4be6-422c-949e-6ebbd4e4a3aa">

### Checklist
- [X] I have followed the issue title guidelines.
- [X] I have clearly described the feature and its approach.
- [X] I have explained the benefits of this feature.
- [X] I have added references or social links, where applicable.
- [X] I have provided additional context, if necessary.
- [X] I have read the GSSOC guidelines and understand the contribution process.
- [X] I have checked for existing issues and pull requests to avoid duplicates.
<img width="926" alt="Screenshot 2024-10-26 at 11 50 45 PM" src="https://github.com/user-attachments/assets/b773f483-087a-4496-b136-b7de658743af">

**Comment by REHAN-18** [comment]
@this-is-yaash pls assign me !!

**Comment by techy4shri** [comment]
Literally copy paste issue as done in twinTrim repo. Redundant and spam.

**Comment by REHAN-18** [comment]
@techy4shri SORRY I haven't read the contribution guidelines !!
