### ISSUE TITLE
Add Dark/Light Mode Toggle Button

### ISSUE THREAD

**Issue by Priyanshu282003** [AmateursLeague/sneaky-package#164]
Description:
Currently, the application lacks an option to switch between dark and light themes. Implementing a toggle button for dark and light modes would enhance user experience by allowing users to choose their preferred theme. This feature is especially beneficial for accessibility and can improve usability in various lighting environments.

Expected Behavior
A toggle button is available on the main interface to switch between dark and light themes.
The selected theme should be retained even after a page refresh or on revisiting the site.
Proposed Solution
UI Design: Add a toggle switch button (e.g., moon/sun icon) to the top navigation bar.
Theme Implementation:
Use CSS variables for color definitions to make switching themes seamless.
Update CSS classes to apply dark or light theme styles.
Storage: Store the user’s theme preference using localStorage or cookies.
Responsiveness: Ensure the toggle button is responsive and easily accessible on both desktop and mobile.
Additional Context
This feature would allow users to personalize their experience and may reduce eye strain for users working in low-light conditions.

**Comment by ShashwatAgrawal20** [comment]
Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/630bac25-8342-43b4-b22d-ad40b61d54a9)


**CLOSING**
