### ISSUE TITLE
Build Script: Write a script that build & deploy the package.

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#167]
Make sure to go through these **Documentation Sections**
1. [Building the Package](https://github.com/AmateursLeague/sneaky-package/blob/main/docs/PyPi_Setup.md#5-building-the-package)
2. [Uploading/Deploying to PyPi](https://github.com/AmateursLeague/sneaky-package/blob/main/docs/PyPi_Setup.md#6-uploading-to-pypi)

---
#### Goal:
This script will guide users through the setup, build, and upload process interactively. 
### Steps

1. **Creating `setup.py` Automatically**
   - We’ll automate writing `setup.py` with prompts for details like `name`, `version`, `packages`, `description`, `author`, `author_email`, `license`, and `install_requires`.
   - This lets users quickly set up their own package details without editing manually.

2. **Building the Package**
   - Run `python setup.py sdist bdist_wheel` to build the package in the root directory once `setup.py` is set up.

3. **Deploying/Uploading to PyPI**
   - Assuming users have a PyPI account, we’ll include `twine` installation: `pip install twine`.
   - Use `twine upload dist/* --username __token__ --password <YOUR_API_TOKEN>`. The script will prompt for the PyPI API token to keep things secure.

**Comment by yashksaini-coder** [comment]
I want to work on this

**Comment by this-is-yaash** [comment]
@yashksaini-coder assigning this to you!🎉
> approach already discussed over discord VC

**Comment by yashksaini-coder** [comment]
@this-is-yaash As we agreed on the VC session, the main approach will be to create a python script which will be used by another user to build the entire package using the setup.py with their own credentials,
Significantly their 
- name of the package
- version
- author
- author's email 
- description (which is optional)

The values will be taken by an .env access method basically.

Furthermore, after that the PyPi token is also given by the user, once they create their own PyPi account and generate a API token for publishing the package under their own name. The API token can be accessed either through the .env file or passed along as an input from the user in the Command line terminal. 

## Summary:

The main objective is to reduce the whole interaction of the user in building their own python library package and setting up the project for **build** & **deploy** stages.

## Optional things to add:

- CMD interaction displaying the status of the process.
- API passed as input, if its not present in the .env file
