### ISSUE TITLE
Copy-to-Clipboard Monitoring

### ISSUE THREAD

**Issue by Anshikapal05** [AmateursLeague/sneaky-package#168]
### Title of the Issue
- [x] **Have you named the issue title clearly and descriptively?**
- [x] **Have you searched for existing issues in the project to avoid duplicates?**

### Approach to Creating This Feature
Capture and log the clipboard contents when certain events occur. This is a simple feature to implement in Python and would demonstrate how sensitive data might be accessed via the clipboard.

### Benefits
Copy-to-Clipboard Monitoring helps identify and log sensitive information copied by users, such as passwords or personal data, highlighting potential security risks. It's a simple way to demonstrate data interception techniques used in cybersecurity assessments.

### Checklist
- [x] I have followed the issue title guidelines.
- [x] I have clearly described the feature and its approach.
- [x] I have explained the benefits of this feature.
- [ ] I have added references or social links, where applicable.
- [ ] I have provided additional context, if necessary.
- [x] I have read the GSSOC guidelines and understand the contribution process.
- [x] I have checked for existing issues and pull requests to avoid duplicates.

**Comment by Anshikapal05** [comment]
@this-is-yaash kindly assign me this. it would be really helpful of you.
thank you

**Comment by techy4shri** [comment]
Uh..we are not here to look for personal data or anything, simply ensuring the pip package deosn't try any sneaky moves, am I correct @this-is-yaash @Wahid7852 @jindalpriyanshu101 @ShashwatAgrawal20 ?
