### ISSUE TITLE
matplotlib_visual /graph.py - Code Snippet Display Function Issues

### ISSUE THREAD

**Issue by Deeptig9138** [AmateursLeague/sneaky-package#17]
File Path Handling: The use of __file__ may fail in interactive environments.
Error Handling: No graceful handling of FileNotFoundError.
Clipboard Copying: Lacks error handling for missing clipboard utilities.
Clarity: Consider adding docstrings and using constants for program paths.

can you please assign this to me @this-is-yaash

**Comment by this-is-yaash** [comment]
Hey @Deeptig9138 , thanks for showing interest in this project!
This project is relatively simple and beginner friendly, but I have not yet documented about "Contribution Guidelines" for new contributors. It'll be easy for you to understand and navigate through the respective files/directories.

I'll finish it within tomorrow and I'll assign this issue to you!
Is that okay? 
> Until then, see how the program has been written and understand what it does!

**Comment by Deeptig9138** [comment]
Thank you so much. As a cybersecurity student it looked like my domain to me. I am looking forward to working on this. Also just a beginner here. Once again thank you

**Comment by this-is-yaash** [comment]
You've come to the right place @Deeptig9138 ; this is a **beginner-friendly** project.

Until the mentors join, I'll be overseeing this project.
Feel free reach out to me if you need assistance! 🙌🏼

**Comment by AnujSaha0111** [comment]
@this-is-yaash can you please assign it to me

**Comment by SHRAVANIc01** [comment]
@this-is-yaash can you please assign it to me

**Comment by this-is-yaash** [comment]
I assigned you @Deeptig9138. Please try to complete it by tomorrow!
Reach out to me if you need assistance, also make sure to update your forked repository with the current upstream repository.

**Comment by this-is-yaash** [comment]
@AnujSaha0111 & @SHRAVANIc01 I will create another 2 issues, make a comment and work on it.

**Comment by this-is-yaash** [comment]
@Deeptig9138 any updates on your PR #35 ?

**Comment by Varun-malviya5** [comment]
hi @this-is-yaash after how many days you will assign this task to others basically i want to do this.

**Comment by Wahid7852** [comment]
Hello @Varun-malviya5, we will wait for Deepti's reply, if no response in the next 24 hours, it will be given to the next contributor interested
