### ISSUE TITLE
Add GIF Title and GitHub Repository Stats to README

### ISSUE THREAD

**Issue by Karthik3904** [AmateursLeague/sneaky-package#173]
### Description
> **Enhancement Proposal**  
> I’d like to suggest adding a GIF as a dynamic title to enhance the visual appeal of the README. Additionally, I propose incorporating GitHub repository stats to provide insights on repository activity and contributions.
>
> **Proposed Changes:**
> 1. **GIF Title**: Replace or enhance the existing title with a short GIF that aligns with the project's theme.
![WhatsApp Image 2024-10-21 at 15 01 28_2cc264e3](https://github.com/user-attachments/assets/672e9be4-e645-4198-aaa7-3893ab52d9e4)

> 2. **GitHub Repository Stats**: Add repository badges, such as stars, forks, and contributions, for better visibility of repository metrics.

https://github.com/user-attachments/assets/6f9aef00-0f73-4743-9aba-92152ac97b2c
>  
> **Benefits**: Improves README aesthetics and gives users a quick overview of the repository’s activity and popularity.
>
> Please let me know if this addition aligns with the project goals. Thank you!

**Comment by techy4shri** [comment]
We don't need this, do not make spam issues or you will be facing consequences @Karthik3904

**Comment by Karthik3904** [comment]
What Kind of spam issue i rised i just planned to give a title in gif format and repository stats in readme. It's not a spam if you dont want these then close this issue dont say that it is a spam

**Comment by techy4shri** [comment]
Currently, any issue which doesn't add value and is raised so will be considered so. Now, you can raise an issue whih aligns with the goals of this repository, for more info, refer to `README.md` or checkout the open issues.
