### ISSUE TITLE
Enhancement: Merging all the offline functions in one module

### ISSUE THREAD

**Issue by tannuiscoding** [AmateursLeague/sneaky-package#185]
### Creating a single module for all the offline working function.
- [x] **Have you named the issue title clearly and descriptively?**
- [x] **Have you searched for existing issues in the project to avoid duplicates?**

### Description

For now, this package has different modules with different features, some work offline and some online. I want to create one module for all the functions which can be used offline in one module in an optimal way. 

I have thought of some sneaky names
-visual.py
-support.py
-graph_utils.py
These kind of names, align with the theme of being sneaky. 

### Approach to Creating This Feature

- There are functions like copy_to_clipboard(), write(), plot() and a few other functions which can be used offline. 
- I I'll merge all these in one file, under the name you suggest.

### Benefits

- it'll make it sneaky
- code would be easily readable and manageable 
- less number of modules with more functionality.

Let me know your thoughts on this and also recommend changes if you feel like.

### Checklist
- [x] I have followed the issue title guidelines.
- [x] I have clearly described the feature and its approach.
- [x] I have explained the benefits of this feature.
- [x] I have added references or social links, where applicable.
- [x] I have provided additional context, if necessary.
- [x] I have read the GSSOC guidelines and understand the contribution process.
- [x] I have checked for existing issues and pull requests to avoid duplicates.

**Comment by ShashwatAgrawal20** [comment]
@this-is-yaash what are your thoughts on this?

**Comment by this-is-yaash** [comment]
@tannuiscoding Initially, we were using those sneaky terms, but it led to confusion. That's why I came up with more straightforward method and feature names, so that the contributors can work on them easily without any doubts!

I think we'll stick with the obvious names, and we'll let the users decide how they want to use them. 


for now, let's go with the current naming conventions that I mentioned in Discord.
> offline(idnt think this name would be good) *lets think about the naming at last, for now > proceed with this*
> - show
>   - show() that list files in `stash/` dir
>   - show("name", pass(int)) -> displays
>   - show("name", pass(int), 1) -> clip copy 
> - clip
>   - clip("name", pass(int)) -> clip cpy
> - write
>   - write("name", pass(int)) -> file write
>
> just offline explanation

**Way of exection**
> ```py
> from package import offline
> offline.show("fileName", 0000)
> ```
> ```py
> from package import offline
> offline.clip("fileName", 0000)
> ```
> ```py
> from package import offline
> offline.write("fileName", 0000)
> ```

**Comment by this-is-yaash** [comment]
> I think we'll stick with the obvious names, and we'll let the users decide how they want to use them.

What I meant is that anyone who clones or downloads this repository can modify the names if they choose. Our goal is to make this main repository more user-friendly and welcoming for contributors.

**Comment by this-is-yaash** [comment]
So far, the current approach seems okay to me 🤷‍♂️
If you guys have a better approach, please share it here!
@ShashwatAgrawal20 @jindalpriyanshu101 @Wahid7852

**Comment by Wahid7852** [comment]
Current approach seems fine to me actually

**Comment by this-is-yaash** [comment]
@tannuiscoding 
## Additional Requirement: 
- Remove the extensions support in all features

**Comment by this-is-yaash** [comment]
@tannuiscoding good work!

## Optimization
- Kept the main functions in a separate directory.
- Used feature files to call the main functions.
- Implemented readable and well-separated modules.

## Additional Requirements
- Removed support for extensions in all features.
- Removed the clipboard copy feature in `show.py`.


> Satisfied with the approach, therefore raising the levels!
