### ISSUE TITLE
Bug: Password validation fails when first digit is `0`

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#186]
#### Error:
```sh
  File "/$(pwd)/sneaky-package/package/est.py", line 2
    display("test", 0844)
                    ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

#### Execution:
```py
from show import display
display("test", 0844)
```

#### Files to fix:
- **`clip.py`**
- **`show.py`**
- **`write.py`**

**Comment by hongan2510** [comment]
hi don't know if you fixed it yet? can you give it to me to have a look to fix it?

**Comment by this-is-yaash** [comment]
@hongan2510 here's the directory link.
https://github.com/AmateursLeague/sneaky-package/tree/main/package

checkout the `clip.py`, `show.py` & `write.py` files in the dir.

**Comment by Wahid7852** [comment]
@hongan2510 if you're working on this issue, let me know, I will assign you here

**Comment by SalimNhiri** [comment]
Hi all, i can work on it, can you please assign me for #186

**Comment by Wahid7852** [comment]
@SalimNhiri currently I believe @hongan2510 is going to work on this guessing on his PR. Let's wait for his confirmation till tomorrow.

**Comment by this-is-yaash** [comment]
# Open for anyone to work on this issue!
> _Comment to get Assigned_

**Comment by yashksaini-coder** [comment]
I want to work on it

**Comment by this-is-yaash** [comment]
@yashksaini-coder you are assigned!
