### ISSUE TITLE
Changes in Code:  Reduce Redundancy in Password Handling

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#187]
### Files:
- **`clip.py`**
- **`show.py`**
- **`write.py`**

These above three files have "_password_" implemented in it, which introduces redundancy. Please refactor this code into a single file, `password.py`, that handles password validation and related logic.

> **Note**: Please ensure that this issue is addressed only after #186 has been resolved. Maintaining the order of these issues is essential.

**Comment by tannuiscoding** [comment]
assign this issue to me. I can work on it.

**Comment by this-is-yaash** [comment]
> Thank you for showing interest, @tannuiscoding. As mentioned in the description, we can proceed with the issue once #186 is closed.

**Comment by this-is-yaash** [comment]
@tannuiscoding you will be assigned once the #186 is resolved!
