### ISSUE TITLE
Enhancement Request: Support for all extensions

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#19]
For now, this only supports files that ends with `.py` extension.
Please change the functionality read any file (such as `.py`, `.js`, `.c`, `cpp`, etc...)
```python
snippet_path = os.path.join(os.path.dirname(__file__), "code_snippets", f"{snippet_name}.py")
```

Do some research and let me know how you plan to work on this!

**Comment by heartofiro** [comment]
Could you assign it to me?
I am a student at the Australian National University, I want to solve it.

**Comment by this-is-yaash** [comment]
@heartofiro assigned this issue to you, under GSSoC'24 Extd.
All the best!

**Comment by this-is-yaash** [comment]
@heartofiro any updates?

**Comment by this-is-yaash** [comment]
@heartofiro 
I'm unassigning you from this issue, due to no progress updates and exceedd time limit!

This issue is now open to everyone, whoever comments first will get it assigned!

**Comment by tannuiscoding** [comment]
assign this issue to me under GSsoc'24 ext.

**Comment by Wahid7852** [comment]
How will you tackle this @tannuiscoding

**Comment by this-is-yaash** [comment]
@Wahid7852 please make sure to instruct the participant to use development branch.
```bash
git fetch origin
git checkout 19-enhancement-request-support-for-all-extensions
```

**Comment by Wahid7852** [comment]
Yes, ofcourse

**Comment by vk-cse** [comment]
can you assign it to me , I can fix this issue. I'll preferred method to fix this issue... kindly assign it to me...

**Comment by this-is-yaash** [comment]
@vk-cse Could you please elaborate on how you are planning work on this?

**Comment by vk-cse** [comment]
@this-is-yaash I'll use manual extension checking method first and add more extensions like .py, .cpp, .js,... and I'll check if the filename.endswith(extension) is matched with filename.extension ....if so return the file else return none(unsupported file).. I would like to work on this issue...kindly assign it to me

**Comment by vk-cse** [comment]
@this-is-yaash  will you assign it to me sir so that I'll proceed further....

**Comment by this-is-yaash** [comment]
@vk-cse seems so far so good!
But i want to support all the extension that were thrown into `stash` directory.

In simple terms, whatever the file that has text in it, it should display it!
can you do that?

I think we can use `regex` to match the extensions, instead of manual check!
Please take your time, conduct research and let me know!

> keep in mind that the goal is to attain a simple solution rather than raising the complexity _bar_!

**Comment by vk-cse** [comment]
@this-is-yaash yes you're right.actually ik you are talking about regex pattern matching , isn't it?... there is many methods to fix this issue like regex , using modules and manual check! I'll try to be optimal ..pls assign it to me

**Comment by this-is-yaash** [comment]
@vk-cse okay then, I'll assign you!

> **Note**: Everything must be executed by using the built-in modules

**Comment by Wahid7852** [comment]
@vk-cse any updates?

**Comment by vk-cse** [comment]
@Wahid7852 I'll update you today...i'm working on it...will update you by EOD

**Comment by this-is-yaash** [comment]
@vk-cse this issue is already past the time limit! and there have been no updates either!

If there's no updates within 60 minutes, it'll be unassigned and open for others to work on!

**Comment by this-is-yaash** [comment]
This issue to open for others to work on!

**Comment by sociallyencrypted** [comment]
Assign it to me, please!

Name: Mehul Arora
Contributing through: GSSoc'24 Ext, Hacktoberfest

**Comment by tannuiscoding** [comment]
Hey @this-is-yaash , I  have read the description of the feature and have looked at code. After reading the code here's my approach that I feel suitable for this feature. 

First change I'll make is in the display function's attributes.  I will take three arguments, snippet_name, password and extention, which I will set to default value as py. 

>Here's the code

```python
def display(snippet_name, password, extension="py"):
       current_time = datetime.now().strftime("%H%M")
        if str(password) != current_time:
            raise ValueError("syntax error")
```

After this,
I will create a list of supported file extensions and check if the extension is supported or not. You can let me know which other extensions do you want to add.

```python
valid_extensions = ["py", "txt", "md"]
    if extension not in valid_extensions:
        raise ValueError(f"Unsupported file extension:")
```

When the list and and the extension is validated, I will implement the function same as before.

```python
snippet_path = os.path.join(
        os.path.dirname(__file__), "stash", f"{snippet_name}.{extension}"
    )
    try:
        base_dir = os.path.dirname(__file__)
        output_path = os.path.join(base_dir, f"{snippet_name}.{extension}")
        shutil.copyfile(snippet_path, output_path)
        print(f"{snippet_name}.{extension} copied successfully.")
    except Exception as e:
        print(f"Syntax Error: {e}")
```


If you think my approach is useful and I should work on this then please assign me this issue under Gssoc-ext.

Thank you.

**Comment by this-is-yaash** [comment]
#110 fixed!
