### ISSUE TITLE
Tests: Write test cases for `offline.py`

### ISSUE THREAD

**Issue by tannuiscoding** [AmateursLeague/sneaky-package#199]
### Title of the Issue
- [x] **Have you named the issue title clearly and descriptively?**
- [x] **Have you searched for existing issues in the project to avoid duplicates?**

### Description

there are no test cases for `offline.py`

### Approach to Creating This Feature

I will write test cases for `offline.py` using pytest and unittests.

### Benefits

it will help in checking the functionality of the code

### Checklist
- [x] I have followed the issue title guidelines.
- [x] I have clearly described the feature and its approach.
- [x] I have explained the benefits of this feature.
- [x] I have added references or social links, where applicable.
- [x] I have provided additional context, if necessary.
- [x] I have read the GSSOC guidelines and understand the contribution process.
- [x] I have checked for existing issues and pull requests to avoid duplicates.

**Comment by this-is-yaash** [comment]
@tannuiscoding you are assigned!

**Comment by ShashwatAgrawal20** [comment]
related to #198 #185

**Comment by yashksaini-coder** [comment]
@tannuiscoding @this-is-yaash 

What you cooking here ??
