### ISSUE TITLE
Bug: [Homepage] Error upon clicking hypertexts on Homepage

### ISSUE THREAD

**Issue by devikaharshey** [AmateursLeague/sneaky-package#208]
### Title of the Issue
- [x] **Have you named the issue title clearly and descriptively?**
- [x] **Have you searched for existing issues in the project to avoid duplicates?**  

### Description

An unexpected behavior is encountered upon clicking hyperlinks on homepage. A default page opens up upon doing so.

### Changes Expected

I will fix the error by removing these default links and adding the required links.

### Screenshots / Logs

![Screenshot 2024-11-09 185625](https://github.com/user-attachments/assets/33c0c756-cc8c-4bf7-b71c-11465940ff60)

### Checklist
- [x] I have followed the issue title guidelines.
- [x] I have included a clear and detailed description.
- [x] I have provided necessary logs, screenshots, or other files.
- [x] I am a GSSOC contributor.
- [ ] I have mentioned related issues or pull requests if any.
- [ ] I have provided details about the environment where the issue was observed.

**Comment by devikaharshey** [comment]
@Wahid7852 please allow me to make these changes and label this as "hacktoberfest-accepted", "gssoc-ext" and "level1" badge.

**Comment by this-is-yaash** [comment]
@devikaharshey sorry it was already fixed in this! #206

**Comment by devikaharshey** [comment]
@this-is-yaash so is there any way I can contribute? please let me know.
