### ISSUE TITLE
Feature Request: Password protection for `graph.py`

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#22]
`graph.py` is a stealthy feature that copies the source code contents into the system clipboard without raising any prompts.

To add another layer of protection, please implement a password requirement when executing it. The password should be linked with the current time.

**Example:** If the time is 12:00:
```python
from package_name.graph import display
display('filename', 1200)
```
This should execute the feature; otherwise, it should simply exit with `exit(1)`.

(or)
If you have a better approach, then please let me know!

**Comment by AnujSaha0111** [comment]
Please assign  it to me. I want to work on it

**Comment by AnujSaha0111** [comment]
I want to work on first solving the display issue of graph.py(visuals) and then on the password protection

**Comment by this-is-yaash** [comment]
Make a comment on the issue I've raised now!
Then I'll assign to you!

**Comment by this-is-yaash** [comment]
Please finish the previous issue, and then I'll assign the new one to you! Until then, it will remain open for everyone. If anyone else wants to work on this issue, just leave a comment, and I'll assign it to you.

**Comment by Virat-Shrimali** [comment]
can you please assign me this issue?

**Comment by this-is-yaash** [comment]
@Virat-Shrimali assinged this to you under GSSoC'24 Extd.
All the best!

**Comment by AnujSaha0111** [comment]
can you please now assign me this issue?

**Comment by AnujSaha0111** [comment]
Can you please assign it to me

**Comment by rohitsharma2610** [comment]
can you please assgin it to me, i know how to solve this,

**Comment by this-is-yaash** [comment]
> can you please assgin it to me, i know how to solve this,

This was already assigned to someone!
Check out other issues in the **Issues** section. Leave a comment on any unassigned issue, and I'll assign it to you!
