### ISSUE TITLE
OS Support: Add iOS support in `graph.py`

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#23]
After using **black linter**, `display()` method in `graph.py` is not working properly.
Find a way to fix it!

**Comment by AnujSaha0111** [comment]
assign it to me.

**Comment by AnujSaha0111** [comment]
Solved the issue and created pull request

**Comment by this-is-yaash** [comment]
I'll let you know after reviewing it!

**Comment by this-is-yaash** [comment]
#32
