### ISSUE TITLE
 Implement robust error handling and logging to provide feedback if an error occurs during execution.

### ISSUE THREAD

**Issue by Kritika75** [AmateursLeague/sneaky-package#27]
Hey, I'm Kritika. I'm a part of GSSoC'24 as a contributor, and I would like to contribute to your project. Can you assign me this with labels?

**Comment by this-is-yaash** [comment]
@Kritika75 Could you please briefly explain what you are planning to do?

**Comment by Kritika75** [comment]
In the original code, there's a part that copies text to the clipboard, but if something goes wrong, the user won't know. For example, if there are permission issues or the clipboard command fails, the code won't show an error. To fix this, we can wrap that part of the code in a try-except block. This will catch any errors that happen, and we can use logging to record the errors and give feedback. By doing this, we make sure that any problems are noticed and dealt with. Handling these errors properly makes sure that the program works safely and reliably.

**Comment by this-is-yaash** [comment]
That makes sense! However, please keep in mind that this Python package integrates source code/information into another computer in a stealthy way. Therefore, I would like to propose the solution differently.

Instead of printing an error message, print a casual message that won't alert the monitoring personnel. It should simply indicate that there's an issue without explicitly stating that there's an error.

**Comment by this-is-yaash** [comment]
Let me know, if you're interested!
Then I'll assign this issue to you under GSSoC'24 Extd.

**Comment by Kritika75** [comment]
Definitely, I'm interested

**Comment by this-is-yaash** [comment]
@Kritika75 I've assigned this issue to you under GSSoC'24 Extd.

**Comment by Kritika75** [comment]
Thank you, I'll start working on it as soon as possible

**Comment by Kritika75** [comment]
@this-is-yaash Yeah, I've started working on it, I will probably send the pull request in 2-3 days.

**Comment by Kritika75** [comment]
By the way, I will make changes and add the features described in graph.py. Don't worry, I follow the style of code and requirements you've mentioned in the README file. I hope that's okay.

**Comment by this-is-yaash** [comment]
@Kritika75 sorry, but you can't take more than 1 day for **`level1`** issue.
If there's no updates, I'll be unassigning the issue and it'll be open for others to work on!

**Comment by Kritika75** [comment]
Apologies for the delay. I was working on other projects as well, which caused the delay. I had thought the coding period would end on 30th October. I can try to complete it by tomorrow, or you can unassign this task to me. Sorry for any inconvenience caused. Thank you.

**Comment by Wahid7852** [comment]
Hey @Kritika75, I will be un-assigning you from this. Hope you have a great day.
