### ISSUE TITLE
New Feature Request: Web scraping from cl1p.net

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#30]
Check out this website: https://cl1p.net  
This is a clipboard website where you can temporarily store your text data.

Create a Python feature that scrapes the data from the site and preprocesses it before displaying. The feature should only display the text content without showing the HTML page.

**How cl1p.net works:**  
By entering a URL name like `cl1p.net/url-name`, you can access the content inside it without authentication.

Create a feature that works as follows:

**Example:**
```python
from package_name.scrape import featureName
featureName('url-name')
```
**Output:**
```bash
Contents of the page at cl1p.net/url-name
```

> I'll leave the naming conventions to you for `scrape` & `featureName`. Come up with a good name!

**Comment by rishikaa1** [comment]
@this-is-yaash Hello, I would like to work on this issue.

**Comment by sajal-11111** [comment]
@this-is-yaash

I'm sajal tyagi. I'm excited about contributing to sneaky packagefor GSoC ext.2024. Could you please assign me a suitable issue to get started? I'm eager to learn and contribute to the project.

**Comment by Patel-Arpita** [comment]
hello , can you please assign it to me ?

**Comment by NavSrijan** [comment]
I would like to work on this issue under GSSoC'24 Extended Edition.

**Comment by JahnaviDhanaSri** [comment]
I’m excited about the cl1p.net Python scraping task and would love to take it on. I have solid experience with requests for fetching data and BeautifulSoup for parsing and cleaning HTML content. I’m confident I can efficiently build a feature that extracts and preprocesses the text content from cl1p.net URLs.
I look forward to contributing and delivering a better solution. Please let me know if I can proceed!

**Comment by this-is-yaash** [comment]
@rishikaa1 assigning this issue to you!
Keep that in mind, it's a new feature
1. You should scrape the url's html content using in-built modules
2. preprocess, and display only the content that was pasted on the clipboard site

**Comment by this-is-yaash** [comment]
@sajal-11111 @Patel-Arpita @NavSrijan @JahnaviDhanaSri 
Thanks for showing interest in this project. I've assigned this someone based on first-come, first-serve basis.

This is a level 3 issue, and if the participant needs assistance, we may pair one of you with them.
In the meantime, please explore the project and feel free to raise/request an issue to work on!

**Comment by rishikaa1** [comment]
@this-is-yaash thanks!

**Comment by this-is-yaash** [comment]
@rishikaa1 any updates?

**Comment by this-is-yaash** [comment]
@rishikaa1 could you please work on this issue using the development branch?
It would be better to track the progress.

Please use the following commands in your environment and make the changes there (inside the checked-out branch)!
```bash
git fetch origin
git checkout 30-new-feature-request-web-scraping-from-cl1pnet
```

**Comment by rishikaa1** [comment]
@this-is-yaash apologies for the oversight but i just created PR. shall i do it again using the development branch?

**Comment by this-is-yaash** [comment]
i think it's fine, i just wanted to streamline the issues and it's relevant PR but you've already mentioned it in PR template. 

No prob! just keep working on the changes I have mentioned in the comment

**Comment by rishikaa1** [comment]
@this-is-yaash yes i am!
