### ISSUE TITLE
check if xclip is installed

### ISSUE THREAD

**Issue by tannuiscoding** [AmateursLeague/sneaky-package#44]
if xclip is missing in Linux provide feedback. it is not installed by default.

**Comment by this-is-yaash** [comment]
Conduct research on this topic, 
- why we need xclip which OS support xclip
- alternatives for other OS


Let me know, what you are planning to do?
(breifly)

**Comment by tannuiscoding** [comment]
This code would run fine on all the systems, but if it runs on a system with Linux, which doesn't have xclip installed, the subprocess.run() would give a file not found error. Xclip is a command line utility which manages the clipboard in Linux.

**Comment by tannuiscoding** [comment]
I want to add "shutil.which("xclip")" in the code to check if xclip is installed or not.

**Comment by Wahid7852** [comment]
We have to make a way where we check the distro, check the desktop environment and then asks the user, in a discrete way, to install the tool respective to the DE (xclip, wclip, etc etc)

Thats the only approach we can do for now without compromising ourselves

**Comment by tannuiscoding** [comment]
I can add code to check if xclip is installed or not. I want to alert the user with a message that xclip is required to run the program smoothly. when xclip is not installed. Assign me this issue under GSsoc'24 ext.

**Comment by Wahid7852** [comment]
okay will do, I am looking forward to your solution
