### ISSUE TITLE
Fix: Error handling in display() function

### ISSUE THREAD

**Issue by Shreya7tripathy** [AmateursLeague/sneaky-package#45]
Hello! I would like to raise an issue regarding the display function in models.py. Currently, the function does not check if the specified file exists before attempting to open it. This can lead to potential errors, such as FileNotFoundError.

I suggest adding:

1.A file existence check using os.path.isfile().
2.Error handling to manage any issues during file reading.
These changes will make the function more robust and user-friendly. If this issue is correct, could you please assign it to me @this-is-yaash ? would greatly appreciate the opportunity to contribute. Thank you!

**Comment by jindalpriyanshu101** [comment]
You're assigned. @Shreya7tripathy

**Comment by Shreya7tripathy** [comment]
@jindalpriyanshu101 I will keep that in mind. Thank you for assigning this to me.
