### ISSUE TITLE
Test: Create test cases for the existing features

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#58]
## Write test cases for the existing three features.

**Ensure you maintain this order**:

```
─ package/
  ├── __init__.py
  ├── graph.py   
  ├── models.py
  └── piechart.py
─ tests/
  ├── __init__.py 
  ├── test_graph.py 
  ├── test_models.py 
  └── test_piechart.py
─ .deepsource.toml
─ .gitignore
─ CHANGELOG.md
─ CODE_OF_CONDUCT.md
─ LICENSE
─ README.md
─ setup.py
```

### Test Case:
- [ ] `graph.py`
- [ ] `models.py`
- [ ] `piechart.py`

I believe it would be tedious task, so please report your progress frequently so I can assist you along the way.
> We may need to make some adjustments to the actual features or implement changes to ensure stable test cases

**Comment by tanuj437** [comment]
I would like to work on this issue under GSSoC'24 Extended Edition.

**Comment by Varun-malviya5** [comment]
hi @this-is-yaash  please assign this task to me

**Comment by Wahid7852** [comment]
How will you be writing test cases for this @Varun-malviya5 @tanuj437 ? Can I know your ideas?

**Comment by tanuj437** [comment]
@Wahid7852 Would go with checking for both cases postive and negative(error one) and also using the unittest framework

**Comment by Varun-malviya5** [comment]
hi @Wahid7852 i will test with the following :
For graphs.py we can Test any traversal (e.g., BFS, DFS), shortest path (e.g., Dijkstra’s), or any other algorithm implemented.
for models.py we can check the Password rotation logic.
Verify that a pie chart generated with a simple dataset is accurate

**Comment by Wahid7852** [comment]
@Varun-malviya5 did you open the files and read them

**Comment by this-is-yaash** [comment]
> hi @Wahid7852 i will test with the following : For graphs.py we can Test any traversal (e.g., BFS, DFS), shortest path (e.g., Dijkstra’s), or any other algorithm implemented. for models.py we can check the Password rotation logic. Verify that a pie chart generated with a simple dataset is accurate

@Varun-malviya5 
I guess you might be using GPTs to answer in comments. Just because the filename is `graph.py` doesn't mean, it's related to graphs. It's just an alias, so I advise you to go through the project.

Keep in mind this is a beginner-friendly project, so you won't be overwhelmed by the codebase. Make sure you check it out and leave a comment. I'll assign this issue to those who do proper research!

**Comment by this-is-yaash** [comment]
> @Wahid7852 Would go with checking for both cases postive and negative(error one) and also using the unittest framework

Hey @tanuj437, thanks for showing interest in this project!
Please fork the repo and try to run the program by yourself. 
See how it works, and try to write the testcase(dummy), it would give you an overview.

Currently we have three features, look into the features and understand what it does!
Write test cases for those 3.

**Comment by this-is-yaash** [comment]
@Wahid7852 @jindalpriyanshu101 I have created development branch for this **test case** issue, make sure the participants use this branch to work on this issue.

```bash
git fetch origin
git switch 58-test-create-test-cases-for-the-existing-features 
```
> Note: Contributors execute this command to switch to this branch and work on it.

**Comment by tannuiscoding** [comment]
Hey @this-is-yaash 

I have gone through the project and seen the functions. I'm interested in writing the test cases for this project. 
Here's my approach to write test cases:
1. I will implement tests for all 3 files, models.py, graph.py and piechart.py using PyTest and Unittest
2. I'll write two test cases for each function, one for the proper functioning and other for checking the except block too.

Here's a sample test case approach for display function from display.py

Kindly correct me if I am wrong anywhere and provide guidance on how can I improve the approch. 


Step1- I will mock the time to a fixed value and check if it reads from the file with correct password 
Step2- I will create another function to check if it raises value error if the password is incorrect. 
```python
from unittest import mock

def mock_datetime_now():
       def now():
               return mock.Mock(hour=12, minute=34)

       return now 
```

after creating this wrong time, I'll compare it with password and will use assert statement to check if it gives the desired output or not.

Please assign me these test cases under gssoc-ext.

Thank you.

**Comment by tannuiscoding** [comment]
hii @this-is-yaash 

I have created two sample cases to check `display()` function in `graph.py`.  I ran those test cases and the test cases failed. 
I have checked the test cases and they are totally correct. Here are the test cases and the result. 
Assign me to write the test cases for rest of the functions and files.

>**code** for the test case.
```python

import pytest
from .graph import display
import datetime

def test_display_right_password():
    assert display("test",1853)== "File Copied"

def test_display_wrong_password():
    current_time = datetime.now().strftime("%H%M")
    assert display("test",current_time) ==  ValueError


```

>**Result** your code is raising attribute error but it should raise value error.

![image](https://github.com/user-attachments/assets/47165ef4-2619-499e-9e53-f255e7b6bf54)

>**Code that has raised error.**

```python
def display(snippet_name, password):
    current_time = datetime.now().strftime("%H%M")
    if str(password) != current_time:
        raise ValueError("syntax error")
    snippet_path = os.path.join(
        os.path.dirname(__file__), "stash", f"{snippet_name}.py"
    )
    try:
        base_dir = os.path.dirname(__file__)
        output_path = os.path.join(base_dir, f"{snippet_name}.py")
        shutil.copyfile(snippet_path, output_path)
        print("File Copied")
    except Exception as e:
        print(f"Syntax Error: {e}")
```

Please assign me to write the test cases for the three files under gssoc-ext label.

**Comment by Wahid7852** [comment]
Looks good! Assigning you @tannuiscoding
