### ISSUE TITLE
Add Issue template

### ISSUE THREAD

**Issue by yashksaini-coder** [AmateursLeague/sneaky-package#65]
I would like to add issues template for 
- Bug Report
- Feature request
- Change in Code

@this-is-yaash Please assign me this issue & add labels to it.

**Comment by jindalpriyanshu101** [comment]
Hey @yashksaini-coder can you also add a commented explanation on proper Issue Title handling?

**Comment by jindalpriyanshu101** [comment]
> > Hey @yashksaini-coder can you also add a commented explanation on proper Issue Title handling?
> 
> @ShashwatAgrawal20 @jindalpriyanshu101
> 
> My approach is to classify issues in 2 categories related to either in code or documentation. Similarly for **Feature Request** A detailed description of their social links & their approach to create a new feature.
> 
> If there are particular requirements from the **PA**, please share I will include them in the templates too.

You might have seen our PR Template. i want you to add similar kind of guide for Title Naming.. @yashksaini-coder

**Comment by yashksaini-coder** [comment]
> > > Hey @yashksaini-coder can you also add a commented explanation on proper Issue Title handling?
> > 
> > 
> > @ShashwatAgrawal20 @jindalpriyanshu101
> > My approach is to classify issues in 2 categories related to either in code or documentation. Similarly for **Feature Request** A detailed description of their social links & their approach to create a new feature.
> > If there are particular requirements from the **PA**, please share I will include them in the templates too.
> 
> You might have seen our PR Template. i want you to add similar kind of guide for Title Naming.. @yashksaini-coder

okh understood @jindalpriyanshu101 assign this issue si i can start working on this.

**Comment by jindalpriyanshu101** [comment]
Assigned, you're good to go ;D

**Comment by yashksaini-coder** [comment]
hey who is the author of this repo

**Comment by jindalpriyanshu101** [comment]
> hey who is the author of this repo

@this-is-yaash
