### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [AmateursLeague/sneaky-package#66]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by ShashwatAgrawal20** [comment]
@Shariq2003 hey, this doesn't add any actual value to the project, one can also see the contributors on the contributors side on the project itself, there's no need to clutter the README.

**Comment by yashksaini-coder** [comment]
yeah this & another contributor @say-het is also spamming these same issues.

**Comment by Shariq2003** [comment]
No @yashksaini-coder @this-is-yaash , actually I raised the issue without looking into the existed issues, that's why created the duplicate issue.
And I just raised the issue only once in this repo.
I apologize for this.
