### ISSUE TITLE
Documentation: Phase 1 - PyPI Package Setup and Deployment

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#68]
This repository contains the codebase for a ready-to-deploy Python package. But currently lacks the documentation on how to do so!

Infact the process will be pretty tedious, if the user doesn't know how to setup & deploy.

This issue aims to create a documentation for "`PyPI Package Setup and Deployment`" as mentioned in the title. The documentation should more be focussed on how the user can setup & deploy it, rather than how the contributor do it.
> i.e. User focussed doc will be the best outcome!

**Instructions:**
- Create `.md` in root directory and work on it(no need to mention about the documentation in any doc file. Will do later)
- Expect the doc-crafting to go through trial & error, so be prepared to make adjustments as needed!

Even though the process might be bit tedious, it has fewer steps than what I've mentioned so please ensure to craft a short & clear document.

**Use this discussion channel to share your thoughts**: [Click here](https://github.com/AmateursLeague/sneaky-package/discussions/67) 
### Discussed in https://github.com/AmateursLeague/sneaky-package/discussions/67

<div type='discussions-op-text'>

<sup>Originally posted by **this-is-yaash** October  5, 2024</sup>
Share your thoughts and ideas about the documentation here!</div>

**Comment by yashksaini-coder** [comment]
Hi, @this-is-yaash I have worked on action workflow that was used to launch a py package.

Can I use that experience and create the documentation.

**Comment by this-is-yaash** [comment]
@yashksaini-coder you've already been assigned! 
We can;t assign multiple issues to the same contributor at once. Please complete your current task and then feel free to request the remaining issue for assignment!

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder you've already been assigned! We can;t assign multiple issues to the same contributor at once. Please complete your current task and then feel free to request the remaining issue for assignment!

can I work on this issue now, @this-is-yaash

**Comment by yasheela-alla** [comment]
@this-is-yaash can you assign this to me?
