### ISSUE TITLE
Documentation: Phase 2 - How to use this package?

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#69]
This issue aims to create the documentation on how to use the package after setting up & deploying it!
> Should be crafted in a way that explain what to do after #68

This is a python package, so
- pip install them
- execute them (simple right?)

But the documentation should contains the information on how to execute the current three features such as:
- `graph.py`
- `models.py`
- `piechart.py`

> Keep in mind, these names are aliases so we have point them out!

Try to add a demo terminal simulation like ASCIINEMA(which emulates the terminal commands in markdown, but not a video)
Check this link to learn more about [ASCIINEMA](https://asciinema.org/)

**Comment by this-is-yaash** [comment]
### Use this discussion channel to explain your ideas and request here after getting approved!
### Discussed in https://github.com/AmateursLeague/sneaky-package/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **this-is-yaash** October  5, 2024</sup>
Share your thoughts & ideas on creating a documentation that explains about execution of the package after setting up & deployment.
> Make sure to use [ASCIINEMA](https://asciinema.org/) for this documentation #69!</div>

**Comment by tannuiscoding** [comment]
> This issue aims to create the documentation on how to use the package after setting up & deploying it!
> 
> > Should be crafted in a way that explain what to do after #68
> 
> This is a python package, so
> 
> * pip install them
> * execute them (simple right?)
> 
> But the documentation should contains the information on how to execute the current three features such as:
> 
> * `graph.py`
> * `models.py`
> * `piechart.py`
> 
> > Keep in mind, these names are aliases so we have point them out!
> 
> Try to add a demo terminal simulation like ASCIINEMA(which emulates the terminal commands in markdown, but not a video) Check this link to learn more about [ASCIINEMA](https://asciinema.org/)

Here's how I'd write the documentation for this.

• I'll write all the steps clearly 
• I'll add screenshots of the commands from asciicinema.
• I'll also a section of common issues, which explains and gives solutions for the issues.

Please assign me this issue under GSsoc'24ext.

**Comment by tannuiscoding** [comment]
Here's how I'd write the documentation for this.

• I'll write all the steps clearly
• I'll add emulation of the commands from asciicinema.

Please assign me this issue under GSsoc'24ext.

**Comment by Wahid7852** [comment]
I'm assigning this issue to you now @tannuiscoding

**Comment by this-is-yaash** [comment]
please use the development branch to work on this issue!

```
git fetch origin
git checkout 69-documentation-phase-2-how-to-use-this-package
```
