### ISSUE TITLE
Create a Jekyll Static Page Site

### ISSUE THREAD

**Issue by yashksaini-coder** [AmateursLeague/sneaky-package#72]
### Title:
Create a Jekyll Static Page Site

### Description:
Adding a new feature of a static page site for this repository using Jekyll. This site will serve as a documentation hub and information portal for the project. Also acts as portable link for your side-project in your portfolio too.

### Steps:
1. Set up a new Jekyll site.
2. Configure the `_config.yml` file with the necessary settings.
3. Create the Basic & standard Jekyll page that is easily deployed from **main** branch.
4. Add a theme to improve the visual appearance.
5. Deploy the Jekyll site using GitHub Pages.

---

@this-is-yaash review and approve this issue to create the Jekyll static page site. Add labels too.

**Comment by yashksaini-coder** [comment]
@this-is-yaash can you assign this issue to me ?

**Comment by Wahid7852** [comment]
@yashksaini-coder assigning you
