### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by shubhagarwal1** [AmateursLeague/sneaky-package#75]
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @yashksaini-coder  please assign this task to me

**Comment by ShashwatAgrawal20** [comment]
@shubhagarwal1 hey, this doesn't add any actual value to the project, one can also see the contributors on the contributors side on the project itself, there's no need to clutter the README.

There are bunch of peeps opening the same issue please do something which actually adds value to the project.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 hey, this doesn't add any actual value to the project, one can also see the contributors on the contributors side on the project itself, there's no need to clutter the README.
> 
> There are bunch of peeps opening the same issue please do something which actually adds value to the project.

okay ma

> @shubhagarwal1 hey, this doesn't add any actual value to the project, one can also see the contributors on the contributors side on the project itself, there's no need to clutter the README.
> 
> There are bunch of peeps opening the same issue please do something which actually adds value to the project.

okay may i make a workflow that add autolabels to the issues opened this will probably reduce the effort of addign labels

**Comment by ShashwatAgrawal20** [comment]
@shubhagarwal1 can you create an another issue regarding the workflow you're talking about.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 can you create an another issue regarding the workflow you're talking about.

Sure!
