### ISSUE TITLE
Create Contributing.md 

### ISSUE THREAD

**Issue by rajatsinghal02** [AmateursLeague/sneaky-package#76]
I want to create a Contributing.md file in the repository so that contributor's can easily understand how to make a issue and how to make a pull Requests.

@jindalpriyanshu101 @Wahid7852 @ShashwatAgrawal20 Please assign this issue to me.

**Comment by Wahid7852** [comment]
Share your ideas here @rajatsinghal02 https://github.com/AmateursLeague/sneaky-package/discussions/53
