### ISSUE TITLE
update pr template 

### ISSUE THREAD

**Issue by priyanshaggarwal001** [AmateursLeague/sneaky-package#92]
I would like to update the template file in which it check for screenshot

**Comment by ShashwatAgrawal20** [comment]
explain your approach, what are you gonna change? I don't think it's quite necessary tho.

**Comment by priyanshaggarwal001** [comment]
well it well be helpful during the pr request like to see what change has been made and to see the screenshot of it 
for better understanding

**Comment by ShashwatAgrawal20** [comment]
I don't  think this add value to the project, you can try contributing to other issues tho.
