### ISSUE TITLE
Implement a Mini Chatbot for Enhanced User Interaction

### ISSUE THREAD

**Issue by DivyaJyothi9** [AmateursLeague/sneaky-package#94]
I would like to propose the addition of a mini chatbot feature to the Icyco website. This chatbot will serve as a virtual assistant, helping users  providing assistance with website navigation.

Kindly assign this issue to me..I would like to contribute.
Kindly add the label Gssoc-ext, Hactoberfest, and level-3..as it needs to integrate.
Thank you!!

**Comment by Wahid7852** [comment]
we are not the icyco website @DivyaJyothi9 

did you check the repo name?

**Comment by DivyaJyothi9** [comment]
> we are not the icyco website @DivyaJyothi9
> 
> did you check the repo name?

Sorry @Wahid7852  sir!! my bad
